export const reviewObject = [
  {
    level: 1,
    levelName: "Remember",
    levelType: "Beginner",
    questionNo: 0,
    linkType: "link",
    link: "https://onlinecourses.nptel.ac.in/noc20_cs03/preview",
  },
  // Level 1 -> Question 1
  {
    level: 1,
    levelName: "Remember",
    levelType: "Beginner",
    questionNo: 1,
    linkType: "video",
    link: "https://youtu.be/yj88AaVJ8QQ",
  },
  {
    level: 1,
    levelName: "Remember",
    levelType: "Beginner",
    questionNo: 1,
    linkType: "video",
    link: "https://youtu.be/gGGHjYbQMvw",
  },
  {
    level: 1,
    levelName: "Remember",
    levelType: "Beginner",
    questionNo: 1,
    linkType: "video",
    link: "https://youtu.be/DRSog3SA4-Y",
  },
  // Level 1 -> Question 2
  {
    level: 1,
    levelName: "Remember",
    levelType: "Beginner",
    questionNo: 2,
    linkType: "video",
    link: "https://youtu.be/w1XdPholzWY",
  },
  {
    level: 1,
    levelName: "Remember",
    levelType: "Beginner",
    questionNo: 2,
    linkType: "video",
    link: "https://youtu.be/64szTfLNu3o",
  },
  {
    level: 1,
    levelName: "Remember",
    levelType: "Beginner",
    questionNo: 2,
    linkType: "video",
    link: "https://youtu.be/-gVcV-OFOyI",
  },
  {
    level: 1,
    levelName: "Remember",
    levelType: "Beginner",
    questionNo: 2,
    linkType: "link",
    link: "https://onlinecourses.nptel.ac.in/noc23_cs29/unit?unit=47&lesson=48",
  },
  // Level 1 -> Question 3
  {
    level: 1,
    levelName: "Remember",
    levelType: "Beginner",
    questionNo: 3,
    linkType: "video",
    link: "https://youtu.be/w1XdPholzWY",
  },
  {
    level: 1,
    levelName: "Remember",
    levelType: "Beginner",
    questionNo: 3,
    linkType: "video",
    link: "https://youtu.be/64szTfLNu3o",
  },
  {
    level: 1,
    levelName: "Remember",
    levelType: "Beginner",
    questionNo: 3,
    linkType: "video",
    link: "https://youtu.be/-gVcV-OFOyI",
  },
  {
    level: 1,
    levelName: "Remember",
    levelType: "Beginner",
    questionNo: 3,
    linkType: "link",
    link: "https://onlinecourses.nptel.ac.in/noc23_cs29/unit?unit=47&lesson=48",
  },
  // Level 1 -> Question 4
  {
    level: 1,
    levelName: "Remember",
    levelType: "Beginner",
    questionNo: 4,
    linkType: "link",
    link: "https://onlinecourses.nptel.ac.in/noc23_cs29/unit?unit=91&lesson=94",
  },
  {
    level: 1,
    levelName: "Remember",
    levelType: "Beginner",
    questionNo: 4,
    linkType: "video",
    link: "https://youtu.be/p4bA-gM8ulQ",
  },
  {
    level: 1,
    levelName: "Remember",
    levelType: "Beginner",
    questionNo: 4,
    linkType: "video",
    link: "https://youtu.be/5ammL5KU4mo",
  },
  {
    level: 1,
    levelName: "Remember",
    levelType: "Beginner",
    questionNo: 4,
    linkType: "video",
    link: "https://youtu.be/IwkLWVBkC74",
  },
  // Level 1 -> Question 5
  {
    level: 1,
    levelName: "Remember",
    levelType: "Beginner",
    questionNo: 5,
    linkType: "video",
    link: "https://youtu.be/64szTfLNu3o",
  },
  {
    level: 1,
    levelName: "Remember",
    levelType: "Beginner",
    questionNo: 5,
    linkType: "video",
    link: "https://youtu.be/w1XdPholzWY",
  },
  // Level 2 -> Question 0
  {
    level: 2,
    levelName: "Understanding",
    levelType: "Beginner",
    questionNo: 0,
    linkType: "link",
    link: "https://nptel.ac.in/courses/106104135",
  },
  // Level 2 -> Question 1
  {
    level: 2,
    levelName: "Understanding",
    levelType: "Beginner",
    questionNo: 1,
    linkType: "video",
    link: "https://youtu.be/64szTfLNu3o",
  },
  {
    level: 2,
    levelName: "Understanding",
    levelType: "Beginner",
    questionNo: 1,
    linkType: "video",
    link: "https://youtu.be/w1XdPholzWY",
  },
  // Level 2 -> Question 2
  {
    level: 2,
    levelName: "Understanding",
    levelType: "Beginner",
    questionNo: 2,
    linkType: "video",
    link: "https://youtu.be/cTSV4bYoxIw",
  },
  {
    level: 2,
    levelName: "Understanding",
    levelType: "Beginner",
    questionNo: 2,
    linkType: "video",
    link: "https://youtu.be/K5jqNjnE-pE",
  },
  // Level 2 -> Question 3
  {
    level: 2,
    levelName: "Understanding",
    levelType: "Beginner",
    questionNo: 3,
    linkType: "video",
    link: "https://youtu.be/PVE4e7_fU0U",
  },
  {
    level: 2,
    levelName: "Understanding",
    levelType: "Beginner",
    questionNo: 3,
    linkType: "video",
    link: "https://youtu.be/TB5T2O8Hwm8",
  },
  // Level 2 -> Question 4
  {
    level: 2,
    levelName: "Understanding",
    levelType: "Beginner",
    questionNo: 4,
    linkType: "video",
    link: "https://youtu.be/PVE4e7_fU0U",
  },
  // Level 2 -> Question 5
  {
    level: 2,
    levelName: "Understanding",
    levelType: "Beginner",
    questionNo: 5,
    linkType: "video",
    link: "https://youtu.be/PVE4e7_fU0U",
  },
  // Level 3 -> Question 0
  {
    level: 3,
    levelName: "Applying",
    levelType: "Intermediate",
    questionNo: 0,
    linkType: "link",
    link: "https://nptel.ac.in/courses/106106093",
  },
  // Level 3 -> Question 1
  {
    level: 3,
    levelName: "Applying",
    levelType: "Intermediate",
    questionNo: 1,
    linkType: "video",
    link: "https://youtu.be/PVE4e7_fU0U",
  },
  // Level 3 -> Question 2
  {
    level: 3,
    levelName: "Applying",
    levelType: "Intermediate",
    questionNo: 2,
    linkType: "video",
    link: "https://youtu.be/sjzlr0EsZL4",
  },
  // Level 3 -> Question 3
  {
    level: 3,
    levelName: "Applying",
    levelType: "Intermediate",
    questionNo: 3,
    linkType: "video",
    link: "https://youtu.be/64szTfLNu3o",
  },
  // Level 3 -> Question 4
  {
    level: 3,
    levelName: "Applying",
    levelType: "Intermediate",
    questionNo: 4,
    linkType: "video",
    link: "https://youtu.be/TB5T2O8Hwm8",
  },
  // Level 3 -> Question 5
  {
    level: 3,
    levelName: "Applying",
    levelType: "Intermediate",
    questionNo: 5,
    linkType: "video",
    link: "https://youtu.be/w1XdPholzWY",
  },
  // Level 4 -> Question 0
  {
    level: 4,
    levelName: "Analyzing",
    levelType: "Advanced",
    questionNo: 0,
    linkType: "link",
    link: "https://nptel.ac.in/courses/106105175",
  },
  // Level 4 -> Question 1
  {
    level: 4,
    levelName: "Analyzing",
    levelType: "Advanced",
    questionNo: 1,
    linkType: "video",
    link: "https://youtu.be/PVE4e7_fU0U",
  },
  // Level 4 -> Question 2
  {
    level: 4,
    levelName: "Analyzing",
    levelType: "Advanced",
    questionNo: 2,
    linkType: "video",
    link: "https://youtu.be/sjzlr0EsZL4",
  },
  // Level 4 -> Question 3
  {
    level: 4,
    levelName: "Analyzing",
    levelType: "Advanced",
    questionNo: 3,
    linkType: "video",
    link: "https://youtu.be/TB5T2O8Hwm8",
  },
  // Level 4 -> Question 4
  {
    level: 4,
    levelName: "Analyzing",
    levelType: "Advanced",
    questionNo: 4,
    linkType: "video",
    link: "https://youtu.be/w1XdPholzWY",
  },
  // Level 4 -> Question 5
  {
    level: 4,
    levelName: "Analyzing",
    levelType: "Advanced",
    questionNo: 5,
    linkType: "video",
    link: "https://youtu.be/ywUn5qNmxNo",
  },
];

// export const CustomURL = "http://localhost:3000";
export const CustomURL = "https://sql-adventure-backend.onrender.com";
